Increment15 17
ilnurmamatkazin/go-devops pull request #11
Opened 2022-03-09 09:23 UTC by ilnurmamatkazin

2022-03-11 18:47 UTC, Perederey requested changes
В целом отлично, добавил комменты по PR,

Но я не вижу две важных штуки для этого инкремента

1) Нет benchmark тестов
2) Нет pprof bin-файлов, которые я бы мог посмотреть

Надо еще разобраться что не так с тестом (возможно ты уже разбираешься), но он должен работать. (это можно сделать и в след спринте, сейчас главное поправить bechmark и pprof

2022-03-11 18:47 UTC, Perederey commented on cmd/agent/main.go
> +	ReportInterval = "1000s"          // период сбора метрик
что-то слишком не часто)

2022-03-11 18:47 UTC, Perederey commented on cmd/agent/main.go
> +	ctx    context.Context // поле с системны контекстом
по-хорошему context не надо хранить в структуре, а передавать первым аргументом в методе.

2022-03-11 18:47 UTC, Perederey commented on cmd/server/handlers/example_test.go
> +	// // Устанавливаем заголовок
эти штуки не должны быть в комментариях

2022-03-11 18:47 UTC, Perederey commented on cmd/server/handlers/getInfo.go
> +// getInfo функция для получения html страницы со значением всех метрик, собранных системой.
заголовок должен начинаться с большой буквы, и соответствовать названию функции

2022-03-11 18:47 UTC, Perederey commented on cmd/server/handlers/getOldMetric.go
> +// getOldMetric устаревшая функция получения значения метрики по ее имени и типу.
тут тоже самое

2022-03-11 18:47 UTC, Perederey commented on cmd/server/handlers/getOldMetric.go
> +	if err := h.Service.GetOldMetric(&metric); err != nil {
А зачем тебе публичный сервис? В handler это не нужно.

2022-03-11 18:47 UTC, Perederey commented on cmd/server/handlers/jsonMetric_test.go
> +			assert.JSONEq(t, string(resBody), tt.want.response)
👍

2022-03-13 10:01 UTC, ilnurmamatkazin commented on cmd/server/handlers/example_test.go
> +	// // Устанавливаем заголовок
Но тогда в этих файлах возникают ошибки не объявленных переменных. Это приемлемо? Если нет, то как быть?

2022-03-13 10:16 UTC, ilnurmamatkazin commented on cmd/server/handlers/getOldMetric.go
> +	if err := h.Service.GetOldMetric(&metric); err != nil {
Если его сделать приватным, то в документации поля для типа Handler получаются не определенными.

![image](https://user-images.githubusercontent.com/93909083/158054869-e7d9fc7e-8008-48d5-88f8-1c8882dbafc6.png)

2022-03-13 11:32 UTC, ilnurmamatkazin commented on cmd/agent/main.go
> +	ReportInterval = "1000s"          // период сбора метрик
В папке profiles 2 профиля, 25 - получен при 200 миллисекунд сборе метрик и 500 миллисекунд отсылки, 26 - получен при 20 миллисекунд сборе метрик и 100 миллисекунд отсылки. Профили получены с помощью команды go tool pprof -http=":9090" -seconds=30 http://localhost:6060/debug/pprof/heap. 
Оба профиля пусты.

2022-03-15 08:23 UTC, Perederey approved these changes
Классно, что добавил профили по памяти

Понимаю, что ты намечался уже с этим PR, но я думаю тема усвоена, хотя есть небольшие мелочи.

И давай про context немного поговорим, как будет время)

2022-03-15 08:23 UTC, Perederey commented on cmd/agent/collect_metrics_test.go
> +			g, ctxGroup = errgroup.WithContext(ctx)
что-то немного тут перемудрил, давай на 1:1 может быть разберем немного про контекст? 
Или я не совсем понимаю, что ты тут хотел)

2022-03-15 18:12 UTC, merged