Increment11 13
ilnurmamatkazin/go-devops pull request #9
Opened 2022-01-27 19:43 UTC by ilnurmamatkazin

2022-02-02 21:46 UTC, lugingf requested changes
Написал комментов

2022-02-02 21:46 UTC, lugingf commented on cmd/server/main.go
> +		log.Println("ошибка подключения к бд: ", err.Error())
Так в почему не завешаем приложение тут?

2022-02-02 21:46 UTC, lugingf commented on cmd/server/handlers/handler_test.go
> +	repository, _ := storage.New(cfg)
Давай ошибку обработаем)

2022-02-02 21:46 UTC, lugingf commented on cmd/server/main_test.go
> +		// TODO: Add test cases.
Давай парочку сделаем?

2022-02-02 21:46 UTC, lugingf commented on cmd/server/service/metric.go
> +		sign := utils.SetHesh(metric.ID, metric.MetricType, s.cfg.Key, metric.Delta, metric.Value)
`Hash`?

2022-02-02 21:46 UTC, lugingf commented on cmd/server/service/metric.go
> +	hash := utils.SetEncodeHesh(metric.ID, metric.MetricType, s.cfg.Key, metric.Delta, metric.Value)
И тут опечатка `Hash`

2022-02-02 21:46 UTC, lugingf commented on cmd/server/service/service_test.go
> +		// TODO: Add test cases.
И тут тесткейсы

2022-02-02 21:46 UTC, lugingf commented on cmd/server/storage/storage.go
> +func New(cfg models.Config) (storage *Storage, err error) {
Давай обзовем `NewStorage()`

2022-02-02 21:46 UTC, lugingf commented on cmd/server/storage/storage.go
> +		go func(s *Storage, i int, d time.Duration) {
Я не уверен, что этому место в конструкторе. Это бы в отдельный публичный метод вынести

2022-02-02 21:46 UTC, lugingf commented on cmd/server/storage/storage.go
> +	s.Lock()
Не ошибка, а вопрос - а зачем нам мютекс при чтении?

2022-02-03 20:09 UTC, ilnurmamatkazin commented on cmd/server/main.go
> +		log.Println("ошибка подключения к бд: ", err.Error())
Я не могу тут завершить приложение, так как в тестах 2-5 нет переменной окружения подключения к базе данных и из-за этого тесты падают.

2022-02-04 16:30 UTC, lugingf commented on cmd/server/main.go
> +		log.Println("ошибка подключения к бд: ", err.Error())
Понял, оке

2022-02-05 18:33 UTC, ilnurmamatkazin commented on cmd/server/storage/storage.go
> +	s.Lock()
Я думал, что чтение из  map тоже не потокозащищенное.
Заменил простой мьютекс на RWMutex.

2022-02-07 09:10 UTC, lugingf commented on cmd/server/storage/storage.go
> +	s.Lock()
Не, только запись опасна. При чтении все хорошо

2022-02-07 09:14 UTC, lugingf approved these changes
Принято, спасибо!

2022-02-07 09:14 UTC, lugingf commented on cmd/server/storage/storage_test.go
> +	// "github.com/stretchr/testify/assert"
На будущее - тут можно почистить

2022-02-07 17:58 UTC, merged